add prepublish script, fixes missing checker.js
Used: `typings-checker test.ts`.
Error: `Cannot find module './checker'`.
Not sure why `index.ts` did have a compiled version!